version: '3.8'
#reference:https://firehydrant.com/blog/develop-a-go-app-with-docker-compose/
services:

 app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Forward the exposed port 4000 on the container to port 4000 on the host machine
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

 db:
    image: redis:alpine
    expose:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
  redis-conf:
    
    
      



#   redis:
#     image: "redis:alpine"
#     command: redis-server
#     expose:
#      - "6379"
#     volumes:
#       - redis-data:/data
#       - redis-conf:/usr/local/etc/redis/redis.conf
# volumes:
#   redis-data:
#   redis-conf:


  
 
